# Generated by Django 3.2.9 on 2021-11-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('text_log', models.CharField(max_length=10000)),
                ('date_add', models.DateTimeField()),
            ],
        ),
    ]
