# Generated by Django 3.2.9 on 2021-11-21 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logs',
            table='domain_logs',
        ),
    ]
