# Generated by Django 3.2.9 on 2021-11-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_logs_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logs',
            table='domain_logs',
        ),
    ]
