# Generated by Django 3.2.9 on 2021-12-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_logs_type_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='type_logs',
            field=models.CharField(max_length=50),
        ),
    ]
